# Run vi mode
set-window-option -g mode-keys vi

# Allow arrow key to be used just after changing window
set-option -g repeat-time 0

# Use C-f, since it's on the home row and easier to hit than C-b
set-option -g prefix C-f
unbind-key C-f
bind-key C-f send-prefix
set -g base-index 1

# Swap windows side
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Label window name to current directory
set-window-option -g window-status-current-format '#[fg=white,bold]** #{window_index} #[fg=green]#{pane_current_command} #[fg=blue]#(echo "#{pane_current_path}" | rev | cut -d'/' -f-3 | rev) #[fg=white]**|'
set-window-option -g window-status-format '#[fg=white,bold]#{window_index} #[fg=green]#{pane_current_command} #[fg=blue]#(echo "#{pane_current_path}" | rev | cut -d'/' -f-3 | rev) #[fg=white]|'

# Set no gap for window index
set-option -g renumber-windows on

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Split panes
bind-key v split-window -h
bind-key s split-window -v

# Switch panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resize panes
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

# Copy / paste config
bind-key [ copy-mode
bind-key ] paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
if-shell "uname | grep -q Linux" \
	"bind-key -T copy-mode-vi y send-keys -X copy-pipe \'xclip -in -selection clipboard\'"
if-shell "[ -z ${WSLENV} ]" \
	"bind-key -T copy-mode-vi y send-keys -X copy-pipe \'tmux save-buffer - | /mnt/c/Windows/System32/clip.exe\'"

# Also, bind-key '{' or '}' will switch your pane position. Maybe useful if you want your command prompt and code editor to swap places
