# run vi mode
set-window-option -g mode-keys vi

# allow arrow key to be used just after changning window
set-option -g repeat-time 0

# automatically set title of window
set-window-option -g automatic-rename on
set-option -g set-titles on

# use C-a, since it's on the home row and easier to hit than C-b
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix
set -g base-index 1

# easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# split panes
bind-key v split-window -h
bind-key s split-window -v

# switch panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# switch windows
bind-key , previous-window 
bind-key . next-window 

# copy / paste config
bind-key [ copy-mode
bind-key ] paste-buffer
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe 'xclip -in -selection clipboard' 
