# Run vi mode
set-window-option -g mode-keys vi

# Allow arrow key to be used just after changing window
set-option -g repeat-time 0

# Automatically set title of window
set-window-option -g automatic-rename on
set-option -g set-titles on

# Use C-f, since it's on the home row and easier to hit than C-b
set-option -g prefix C-f
unbind-key C-f
bind-key C-f send-prefix
set -g base-index 1

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Split panes
bind-key v split-window -h
bind-key s split-window -v

# Switch panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resize panes
bind J resize-pane -D 2
bind K resize-pane -U 2
bind L resize-pane -L 2
bind H resize-pane -R 2

# Switch windows
bind-key , previous-window 
bind-key . next-window 

# Copy / paste config
bind-key [ copy-mode
bind-key ] paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
if-shell "uname | grep -q Linux" "bind-key -T copy-mode-vi y send-keys -X copy-pipe \'xclip -in -selection clipboard\'"
